# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/busy/workspace/hxf

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/busy/workspace/hxf

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/busy/workspace/hxf/CMakeFiles /home/busy/workspace/hxf/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/busy/workspace/hxf/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named my_http_server

# Build rule for target.
my_http_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 my_http_server
.PHONY : my_http_server

# fast build rule for target.
my_http_server/fast:
	$(MAKE) -f CMakeFiles/my_http_server.dir/build.make CMakeFiles/my_http_server.dir/build
.PHONY : my_http_server/fast

#=============================================================================
# Target rules for targets named echo_server

# Build rule for target.
echo_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echo_server
.PHONY : echo_server

# fast build rule for target.
echo_server/fast:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/build
.PHONY : echo_server/fast

#=============================================================================
# Target rules for targets named test_http_connection

# Build rule for target.
test_http_connection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http_connection
.PHONY : test_http_connection

# fast build rule for target.
test_http_connection/fast:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/build
.PHONY : test_http_connection/fast

#=============================================================================
# Target rules for targets named test_http

# Build rule for target.
test_http: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http
.PHONY : test_http

# fast build rule for target.
test_http/fast:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/build
.PHONY : test_http/fast

#=============================================================================
# Target rules for targets named test_config

# Build rule for target.
test_config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_config
.PHONY : test_config

# fast build rule for target.
test_config/fast:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/build
.PHONY : test_config/fast

#=============================================================================
# Target rules for targets named test_http_parser

# Build rule for target.
test_http_parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http_parser
.PHONY : test_http_parser

# fast build rule for target.
test_http_parser/fast:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/build
.PHONY : test_http_parser/fast

#=============================================================================
# Target rules for targets named hxf

# Build rule for target.
hxf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hxf
.PHONY : hxf

# fast build rule for target.
hxf/fast:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/build
.PHONY : hxf/fast

#=============================================================================
# Target rules for targets named test_tcp_server

# Build rule for target.
test_tcp_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_tcp_server
.PHONY : test_tcp_server

# fast build rule for target.
test_tcp_server/fast:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/build
.PHONY : test_tcp_server/fast

#=============================================================================
# Target rules for targets named test_bytearray

# Build rule for target.
test_bytearray: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_bytearray
.PHONY : test_bytearray

# fast build rule for target.
test_bytearray/fast:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/build
.PHONY : test_bytearray/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named test_thread

# Build rule for target.
test_thread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_thread
.PHONY : test_thread

# fast build rule for target.
test_thread/fast:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/build
.PHONY : test_thread/fast

#=============================================================================
# Target rules for targets named test_util

# Build rule for target.
test_util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_util
.PHONY : test_util

# fast build rule for target.
test_util/fast:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/build
.PHONY : test_util/fast

#=============================================================================
# Target rules for targets named test_fiber

# Build rule for target.
test_fiber: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_fiber
.PHONY : test_fiber

# fast build rule for target.
test_fiber/fast:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/build
.PHONY : test_fiber/fast

#=============================================================================
# Target rules for targets named test_http_server

# Build rule for target.
test_http_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http_server
.PHONY : test_http_server

# fast build rule for target.
test_http_server/fast:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/build
.PHONY : test_http_server/fast

#=============================================================================
# Target rules for targets named test_address

# Build rule for target.
test_address: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_address
.PHONY : test_address

# fast build rule for target.
test_address/fast:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/build
.PHONY : test_address/fast

#=============================================================================
# Target rules for targets named test_scheduler

# Build rule for target.
test_scheduler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_scheduler
.PHONY : test_scheduler

# fast build rule for target.
test_scheduler/fast:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/build
.PHONY : test_scheduler/fast

#=============================================================================
# Target rules for targets named test_iomanager

# Build rule for target.
test_iomanager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_iomanager
.PHONY : test_iomanager

# fast build rule for target.
test_iomanager/fast:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/build
.PHONY : test_iomanager/fast

#=============================================================================
# Target rules for targets named test_hook

# Build rule for target.
test_hook: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_hook
.PHONY : test_hook

# fast build rule for target.
test_hook/fast:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/build
.PHONY : test_hook/fast

#=============================================================================
# Target rules for targets named test_socket

# Build rule for target.
test_socket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_socket
.PHONY : test_socket

# fast build rule for target.
test_socket/fast:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/build
.PHONY : test_socket/fast

example/echo_server.o: example/echo_server.cc.o

.PHONY : example/echo_server.o

# target to build an object file
example/echo_server.cc.o:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/example/echo_server.cc.o
.PHONY : example/echo_server.cc.o

example/echo_server.i: example/echo_server.cc.i

.PHONY : example/echo_server.i

# target to preprocess a source file
example/echo_server.cc.i:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/example/echo_server.cc.i
.PHONY : example/echo_server.cc.i

example/echo_server.s: example/echo_server.cc.s

.PHONY : example/echo_server.s

# target to generate assembly for a file
example/echo_server.cc.s:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/example/echo_server.cc.s
.PHONY : example/echo_server.cc.s

hxf/address.o: hxf/address.cc.o

.PHONY : hxf/address.o

# target to build an object file
hxf/address.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/address.cc.o
.PHONY : hxf/address.cc.o

hxf/address.i: hxf/address.cc.i

.PHONY : hxf/address.i

# target to preprocess a source file
hxf/address.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/address.cc.i
.PHONY : hxf/address.cc.i

hxf/address.s: hxf/address.cc.s

.PHONY : hxf/address.s

# target to generate assembly for a file
hxf/address.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/address.cc.s
.PHONY : hxf/address.cc.s

hxf/bytearray.o: hxf/bytearray.cc.o

.PHONY : hxf/bytearray.o

# target to build an object file
hxf/bytearray.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/bytearray.cc.o
.PHONY : hxf/bytearray.cc.o

hxf/bytearray.i: hxf/bytearray.cc.i

.PHONY : hxf/bytearray.i

# target to preprocess a source file
hxf/bytearray.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/bytearray.cc.i
.PHONY : hxf/bytearray.cc.i

hxf/bytearray.s: hxf/bytearray.cc.s

.PHONY : hxf/bytearray.s

# target to generate assembly for a file
hxf/bytearray.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/bytearray.cc.s
.PHONY : hxf/bytearray.cc.s

hxf/config.o: hxf/config.cc.o

.PHONY : hxf/config.o

# target to build an object file
hxf/config.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/config.cc.o
.PHONY : hxf/config.cc.o

hxf/config.i: hxf/config.cc.i

.PHONY : hxf/config.i

# target to preprocess a source file
hxf/config.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/config.cc.i
.PHONY : hxf/config.cc.i

hxf/config.s: hxf/config.cc.s

.PHONY : hxf/config.s

# target to generate assembly for a file
hxf/config.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/config.cc.s
.PHONY : hxf/config.cc.s

hxf/fd_manager.o: hxf/fd_manager.cc.o

.PHONY : hxf/fd_manager.o

# target to build an object file
hxf/fd_manager.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/fd_manager.cc.o
.PHONY : hxf/fd_manager.cc.o

hxf/fd_manager.i: hxf/fd_manager.cc.i

.PHONY : hxf/fd_manager.i

# target to preprocess a source file
hxf/fd_manager.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/fd_manager.cc.i
.PHONY : hxf/fd_manager.cc.i

hxf/fd_manager.s: hxf/fd_manager.cc.s

.PHONY : hxf/fd_manager.s

# target to generate assembly for a file
hxf/fd_manager.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/fd_manager.cc.s
.PHONY : hxf/fd_manager.cc.s

hxf/fiber.o: hxf/fiber.cc.o

.PHONY : hxf/fiber.o

# target to build an object file
hxf/fiber.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/fiber.cc.o
.PHONY : hxf/fiber.cc.o

hxf/fiber.i: hxf/fiber.cc.i

.PHONY : hxf/fiber.i

# target to preprocess a source file
hxf/fiber.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/fiber.cc.i
.PHONY : hxf/fiber.cc.i

hxf/fiber.s: hxf/fiber.cc.s

.PHONY : hxf/fiber.s

# target to generate assembly for a file
hxf/fiber.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/fiber.cc.s
.PHONY : hxf/fiber.cc.s

hxf/hook.o: hxf/hook.cc.o

.PHONY : hxf/hook.o

# target to build an object file
hxf/hook.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/hook.cc.o
.PHONY : hxf/hook.cc.o

hxf/hook.i: hxf/hook.cc.i

.PHONY : hxf/hook.i

# target to preprocess a source file
hxf/hook.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/hook.cc.i
.PHONY : hxf/hook.cc.i

hxf/hook.s: hxf/hook.cc.s

.PHONY : hxf/hook.s

# target to generate assembly for a file
hxf/hook.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/hook.cc.s
.PHONY : hxf/hook.cc.s

hxf/http/http.o: hxf/http/http.cc.o

.PHONY : hxf/http/http.o

# target to build an object file
hxf/http/http.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/http.cc.o
.PHONY : hxf/http/http.cc.o

hxf/http/http.i: hxf/http/http.cc.i

.PHONY : hxf/http/http.i

# target to preprocess a source file
hxf/http/http.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/http.cc.i
.PHONY : hxf/http/http.cc.i

hxf/http/http.s: hxf/http/http.cc.s

.PHONY : hxf/http/http.s

# target to generate assembly for a file
hxf/http/http.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/http.cc.s
.PHONY : hxf/http/http.cc.s

hxf/http/http11_parser.rl.o: hxf/http/http11_parser.rl.cc.o

.PHONY : hxf/http/http11_parser.rl.o

# target to build an object file
hxf/http/http11_parser.rl.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/http11_parser.rl.cc.o
.PHONY : hxf/http/http11_parser.rl.cc.o

hxf/http/http11_parser.rl.i: hxf/http/http11_parser.rl.cc.i

.PHONY : hxf/http/http11_parser.rl.i

# target to preprocess a source file
hxf/http/http11_parser.rl.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/http11_parser.rl.cc.i
.PHONY : hxf/http/http11_parser.rl.cc.i

hxf/http/http11_parser.rl.s: hxf/http/http11_parser.rl.cc.s

.PHONY : hxf/http/http11_parser.rl.s

# target to generate assembly for a file
hxf/http/http11_parser.rl.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/http11_parser.rl.cc.s
.PHONY : hxf/http/http11_parser.rl.cc.s

hxf/http/http_connection.o: hxf/http/http_connection.cc.o

.PHONY : hxf/http/http_connection.o

# target to build an object file
hxf/http/http_connection.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/http_connection.cc.o
.PHONY : hxf/http/http_connection.cc.o

hxf/http/http_connection.i: hxf/http/http_connection.cc.i

.PHONY : hxf/http/http_connection.i

# target to preprocess a source file
hxf/http/http_connection.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/http_connection.cc.i
.PHONY : hxf/http/http_connection.cc.i

hxf/http/http_connection.s: hxf/http/http_connection.cc.s

.PHONY : hxf/http/http_connection.s

# target to generate assembly for a file
hxf/http/http_connection.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/http_connection.cc.s
.PHONY : hxf/http/http_connection.cc.s

hxf/http/http_parser.o: hxf/http/http_parser.cc.o

.PHONY : hxf/http/http_parser.o

# target to build an object file
hxf/http/http_parser.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/http_parser.cc.o
.PHONY : hxf/http/http_parser.cc.o

hxf/http/http_parser.i: hxf/http/http_parser.cc.i

.PHONY : hxf/http/http_parser.i

# target to preprocess a source file
hxf/http/http_parser.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/http_parser.cc.i
.PHONY : hxf/http/http_parser.cc.i

hxf/http/http_parser.s: hxf/http/http_parser.cc.s

.PHONY : hxf/http/http_parser.s

# target to generate assembly for a file
hxf/http/http_parser.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/http_parser.cc.s
.PHONY : hxf/http/http_parser.cc.s

hxf/http/http_server.o: hxf/http/http_server.cc.o

.PHONY : hxf/http/http_server.o

# target to build an object file
hxf/http/http_server.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/http_server.cc.o
.PHONY : hxf/http/http_server.cc.o

hxf/http/http_server.i: hxf/http/http_server.cc.i

.PHONY : hxf/http/http_server.i

# target to preprocess a source file
hxf/http/http_server.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/http_server.cc.i
.PHONY : hxf/http/http_server.cc.i

hxf/http/http_server.s: hxf/http/http_server.cc.s

.PHONY : hxf/http/http_server.s

# target to generate assembly for a file
hxf/http/http_server.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/http_server.cc.s
.PHONY : hxf/http/http_server.cc.s

hxf/http/http_session.o: hxf/http/http_session.cc.o

.PHONY : hxf/http/http_session.o

# target to build an object file
hxf/http/http_session.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/http_session.cc.o
.PHONY : hxf/http/http_session.cc.o

hxf/http/http_session.i: hxf/http/http_session.cc.i

.PHONY : hxf/http/http_session.i

# target to preprocess a source file
hxf/http/http_session.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/http_session.cc.i
.PHONY : hxf/http/http_session.cc.i

hxf/http/http_session.s: hxf/http/http_session.cc.s

.PHONY : hxf/http/http_session.s

# target to generate assembly for a file
hxf/http/http_session.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/http_session.cc.s
.PHONY : hxf/http/http_session.cc.s

hxf/http/httpclient_parser.rl.o: hxf/http/httpclient_parser.rl.cc.o

.PHONY : hxf/http/httpclient_parser.rl.o

# target to build an object file
hxf/http/httpclient_parser.rl.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/httpclient_parser.rl.cc.o
.PHONY : hxf/http/httpclient_parser.rl.cc.o

hxf/http/httpclient_parser.rl.i: hxf/http/httpclient_parser.rl.cc.i

.PHONY : hxf/http/httpclient_parser.rl.i

# target to preprocess a source file
hxf/http/httpclient_parser.rl.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/httpclient_parser.rl.cc.i
.PHONY : hxf/http/httpclient_parser.rl.cc.i

hxf/http/httpclient_parser.rl.s: hxf/http/httpclient_parser.rl.cc.s

.PHONY : hxf/http/httpclient_parser.rl.s

# target to generate assembly for a file
hxf/http/httpclient_parser.rl.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/httpclient_parser.rl.cc.s
.PHONY : hxf/http/httpclient_parser.rl.cc.s

hxf/http/servlet.o: hxf/http/servlet.cc.o

.PHONY : hxf/http/servlet.o

# target to build an object file
hxf/http/servlet.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/servlet.cc.o
.PHONY : hxf/http/servlet.cc.o

hxf/http/servlet.i: hxf/http/servlet.cc.i

.PHONY : hxf/http/servlet.i

# target to preprocess a source file
hxf/http/servlet.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/servlet.cc.i
.PHONY : hxf/http/servlet.cc.i

hxf/http/servlet.s: hxf/http/servlet.cc.s

.PHONY : hxf/http/servlet.s

# target to generate assembly for a file
hxf/http/servlet.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/http/servlet.cc.s
.PHONY : hxf/http/servlet.cc.s

hxf/iomanager.o: hxf/iomanager.cc.o

.PHONY : hxf/iomanager.o

# target to build an object file
hxf/iomanager.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/iomanager.cc.o
.PHONY : hxf/iomanager.cc.o

hxf/iomanager.i: hxf/iomanager.cc.i

.PHONY : hxf/iomanager.i

# target to preprocess a source file
hxf/iomanager.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/iomanager.cc.i
.PHONY : hxf/iomanager.cc.i

hxf/iomanager.s: hxf/iomanager.cc.s

.PHONY : hxf/iomanager.s

# target to generate assembly for a file
hxf/iomanager.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/iomanager.cc.s
.PHONY : hxf/iomanager.cc.s

hxf/log.o: hxf/log.cc.o

.PHONY : hxf/log.o

# target to build an object file
hxf/log.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/log.cc.o
.PHONY : hxf/log.cc.o

hxf/log.i: hxf/log.cc.i

.PHONY : hxf/log.i

# target to preprocess a source file
hxf/log.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/log.cc.i
.PHONY : hxf/log.cc.i

hxf/log.s: hxf/log.cc.s

.PHONY : hxf/log.s

# target to generate assembly for a file
hxf/log.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/log.cc.s
.PHONY : hxf/log.cc.s

hxf/scheduler.o: hxf/scheduler.cc.o

.PHONY : hxf/scheduler.o

# target to build an object file
hxf/scheduler.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/scheduler.cc.o
.PHONY : hxf/scheduler.cc.o

hxf/scheduler.i: hxf/scheduler.cc.i

.PHONY : hxf/scheduler.i

# target to preprocess a source file
hxf/scheduler.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/scheduler.cc.i
.PHONY : hxf/scheduler.cc.i

hxf/scheduler.s: hxf/scheduler.cc.s

.PHONY : hxf/scheduler.s

# target to generate assembly for a file
hxf/scheduler.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/scheduler.cc.s
.PHONY : hxf/scheduler.cc.s

hxf/socket.o: hxf/socket.cc.o

.PHONY : hxf/socket.o

# target to build an object file
hxf/socket.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/socket.cc.o
.PHONY : hxf/socket.cc.o

hxf/socket.i: hxf/socket.cc.i

.PHONY : hxf/socket.i

# target to preprocess a source file
hxf/socket.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/socket.cc.i
.PHONY : hxf/socket.cc.i

hxf/socket.s: hxf/socket.cc.s

.PHONY : hxf/socket.s

# target to generate assembly for a file
hxf/socket.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/socket.cc.s
.PHONY : hxf/socket.cc.s

hxf/socket_stream.o: hxf/socket_stream.cc.o

.PHONY : hxf/socket_stream.o

# target to build an object file
hxf/socket_stream.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/socket_stream.cc.o
.PHONY : hxf/socket_stream.cc.o

hxf/socket_stream.i: hxf/socket_stream.cc.i

.PHONY : hxf/socket_stream.i

# target to preprocess a source file
hxf/socket_stream.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/socket_stream.cc.i
.PHONY : hxf/socket_stream.cc.i

hxf/socket_stream.s: hxf/socket_stream.cc.s

.PHONY : hxf/socket_stream.s

# target to generate assembly for a file
hxf/socket_stream.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/socket_stream.cc.s
.PHONY : hxf/socket_stream.cc.s

hxf/stream.o: hxf/stream.cc.o

.PHONY : hxf/stream.o

# target to build an object file
hxf/stream.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/stream.cc.o
.PHONY : hxf/stream.cc.o

hxf/stream.i: hxf/stream.cc.i

.PHONY : hxf/stream.i

# target to preprocess a source file
hxf/stream.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/stream.cc.i
.PHONY : hxf/stream.cc.i

hxf/stream.s: hxf/stream.cc.s

.PHONY : hxf/stream.s

# target to generate assembly for a file
hxf/stream.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/stream.cc.s
.PHONY : hxf/stream.cc.s

hxf/tcp_server.o: hxf/tcp_server.cc.o

.PHONY : hxf/tcp_server.o

# target to build an object file
hxf/tcp_server.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/tcp_server.cc.o
.PHONY : hxf/tcp_server.cc.o

hxf/tcp_server.i: hxf/tcp_server.cc.i

.PHONY : hxf/tcp_server.i

# target to preprocess a source file
hxf/tcp_server.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/tcp_server.cc.i
.PHONY : hxf/tcp_server.cc.i

hxf/tcp_server.s: hxf/tcp_server.cc.s

.PHONY : hxf/tcp_server.s

# target to generate assembly for a file
hxf/tcp_server.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/tcp_server.cc.s
.PHONY : hxf/tcp_server.cc.s

hxf/thread.o: hxf/thread.cc.o

.PHONY : hxf/thread.o

# target to build an object file
hxf/thread.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/thread.cc.o
.PHONY : hxf/thread.cc.o

hxf/thread.i: hxf/thread.cc.i

.PHONY : hxf/thread.i

# target to preprocess a source file
hxf/thread.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/thread.cc.i
.PHONY : hxf/thread.cc.i

hxf/thread.s: hxf/thread.cc.s

.PHONY : hxf/thread.s

# target to generate assembly for a file
hxf/thread.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/thread.cc.s
.PHONY : hxf/thread.cc.s

hxf/timer.o: hxf/timer.cc.o

.PHONY : hxf/timer.o

# target to build an object file
hxf/timer.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/timer.cc.o
.PHONY : hxf/timer.cc.o

hxf/timer.i: hxf/timer.cc.i

.PHONY : hxf/timer.i

# target to preprocess a source file
hxf/timer.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/timer.cc.i
.PHONY : hxf/timer.cc.i

hxf/timer.s: hxf/timer.cc.s

.PHONY : hxf/timer.s

# target to generate assembly for a file
hxf/timer.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/timer.cc.s
.PHONY : hxf/timer.cc.s

hxf/uri.rl.o: hxf/uri.rl.cc.o

.PHONY : hxf/uri.rl.o

# target to build an object file
hxf/uri.rl.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/uri.rl.cc.o
.PHONY : hxf/uri.rl.cc.o

hxf/uri.rl.i: hxf/uri.rl.cc.i

.PHONY : hxf/uri.rl.i

# target to preprocess a source file
hxf/uri.rl.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/uri.rl.cc.i
.PHONY : hxf/uri.rl.cc.i

hxf/uri.rl.s: hxf/uri.rl.cc.s

.PHONY : hxf/uri.rl.s

# target to generate assembly for a file
hxf/uri.rl.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/uri.rl.cc.s
.PHONY : hxf/uri.rl.cc.s

hxf/util.o: hxf/util.cc.o

.PHONY : hxf/util.o

# target to build an object file
hxf/util.cc.o:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/util.cc.o
.PHONY : hxf/util.cc.o

hxf/util.i: hxf/util.cc.i

.PHONY : hxf/util.i

# target to preprocess a source file
hxf/util.cc.i:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/util.cc.i
.PHONY : hxf/util.cc.i

hxf/util.s: hxf/util.cc.s

.PHONY : hxf/util.s

# target to generate assembly for a file
hxf/util.cc.s:
	$(MAKE) -f CMakeFiles/hxf.dir/build.make CMakeFiles/hxf.dir/hxf/util.cc.s
.PHONY : hxf/util.cc.s

sample/my_http_server.o: sample/my_http_server.cc.o

.PHONY : sample/my_http_server.o

# target to build an object file
sample/my_http_server.cc.o:
	$(MAKE) -f CMakeFiles/my_http_server.dir/build.make CMakeFiles/my_http_server.dir/sample/my_http_server.cc.o
.PHONY : sample/my_http_server.cc.o

sample/my_http_server.i: sample/my_http_server.cc.i

.PHONY : sample/my_http_server.i

# target to preprocess a source file
sample/my_http_server.cc.i:
	$(MAKE) -f CMakeFiles/my_http_server.dir/build.make CMakeFiles/my_http_server.dir/sample/my_http_server.cc.i
.PHONY : sample/my_http_server.cc.i

sample/my_http_server.s: sample/my_http_server.cc.s

.PHONY : sample/my_http_server.s

# target to generate assembly for a file
sample/my_http_server.cc.s:
	$(MAKE) -f CMakeFiles/my_http_server.dir/build.make CMakeFiles/my_http_server.dir/sample/my_http_server.cc.s
.PHONY : sample/my_http_server.cc.s

tests/test.o: tests/test.cc.o

.PHONY : tests/test.o

# target to build an object file
tests/test.cc.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.o
.PHONY : tests/test.cc.o

tests/test.i: tests/test.cc.i

.PHONY : tests/test.i

# target to preprocess a source file
tests/test.cc.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.i
.PHONY : tests/test.cc.i

tests/test.s: tests/test.cc.s

.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.cc.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.s
.PHONY : tests/test.cc.s

tests/test_address.o: tests/test_address.cc.o

.PHONY : tests/test_address.o

# target to build an object file
tests/test_address.cc.o:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cc.o
.PHONY : tests/test_address.cc.o

tests/test_address.i: tests/test_address.cc.i

.PHONY : tests/test_address.i

# target to preprocess a source file
tests/test_address.cc.i:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cc.i
.PHONY : tests/test_address.cc.i

tests/test_address.s: tests/test_address.cc.s

.PHONY : tests/test_address.s

# target to generate assembly for a file
tests/test_address.cc.s:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cc.s
.PHONY : tests/test_address.cc.s

tests/test_bytearray.o: tests/test_bytearray.cc.o

.PHONY : tests/test_bytearray.o

# target to build an object file
tests/test_bytearray.cc.o:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cc.o
.PHONY : tests/test_bytearray.cc.o

tests/test_bytearray.i: tests/test_bytearray.cc.i

.PHONY : tests/test_bytearray.i

# target to preprocess a source file
tests/test_bytearray.cc.i:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cc.i
.PHONY : tests/test_bytearray.cc.i

tests/test_bytearray.s: tests/test_bytearray.cc.s

.PHONY : tests/test_bytearray.s

# target to generate assembly for a file
tests/test_bytearray.cc.s:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cc.s
.PHONY : tests/test_bytearray.cc.s

tests/test_config.o: tests/test_config.cc.o

.PHONY : tests/test_config.o

# target to build an object file
tests/test_config.cc.o:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.o
.PHONY : tests/test_config.cc.o

tests/test_config.i: tests/test_config.cc.i

.PHONY : tests/test_config.i

# target to preprocess a source file
tests/test_config.cc.i:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.i
.PHONY : tests/test_config.cc.i

tests/test_config.s: tests/test_config.cc.s

.PHONY : tests/test_config.s

# target to generate assembly for a file
tests/test_config.cc.s:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.s
.PHONY : tests/test_config.cc.s

tests/test_fiber.o: tests/test_fiber.cc.o

.PHONY : tests/test_fiber.o

# target to build an object file
tests/test_fiber.cc.o:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.o
.PHONY : tests/test_fiber.cc.o

tests/test_fiber.i: tests/test_fiber.cc.i

.PHONY : tests/test_fiber.i

# target to preprocess a source file
tests/test_fiber.cc.i:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.i
.PHONY : tests/test_fiber.cc.i

tests/test_fiber.s: tests/test_fiber.cc.s

.PHONY : tests/test_fiber.s

# target to generate assembly for a file
tests/test_fiber.cc.s:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.s
.PHONY : tests/test_fiber.cc.s

tests/test_hook.o: tests/test_hook.cc.o

.PHONY : tests/test_hook.o

# target to build an object file
tests/test_hook.cc.o:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cc.o
.PHONY : tests/test_hook.cc.o

tests/test_hook.i: tests/test_hook.cc.i

.PHONY : tests/test_hook.i

# target to preprocess a source file
tests/test_hook.cc.i:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cc.i
.PHONY : tests/test_hook.cc.i

tests/test_hook.s: tests/test_hook.cc.s

.PHONY : tests/test_hook.s

# target to generate assembly for a file
tests/test_hook.cc.s:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cc.s
.PHONY : tests/test_hook.cc.s

tests/test_http.o: tests/test_http.cc.o

.PHONY : tests/test_http.o

# target to build an object file
tests/test_http.cc.o:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cc.o
.PHONY : tests/test_http.cc.o

tests/test_http.i: tests/test_http.cc.i

.PHONY : tests/test_http.i

# target to preprocess a source file
tests/test_http.cc.i:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cc.i
.PHONY : tests/test_http.cc.i

tests/test_http.s: tests/test_http.cc.s

.PHONY : tests/test_http.s

# target to generate assembly for a file
tests/test_http.cc.s:
	$(MAKE) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cc.s
.PHONY : tests/test_http.cc.s

tests/test_http_connection.o: tests/test_http_connection.cc.o

.PHONY : tests/test_http_connection.o

# target to build an object file
tests/test_http_connection.cc.o:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_http_connection.cc.o
.PHONY : tests/test_http_connection.cc.o

tests/test_http_connection.i: tests/test_http_connection.cc.i

.PHONY : tests/test_http_connection.i

# target to preprocess a source file
tests/test_http_connection.cc.i:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_http_connection.cc.i
.PHONY : tests/test_http_connection.cc.i

tests/test_http_connection.s: tests/test_http_connection.cc.s

.PHONY : tests/test_http_connection.s

# target to generate assembly for a file
tests/test_http_connection.cc.s:
	$(MAKE) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_http_connection.cc.s
.PHONY : tests/test_http_connection.cc.s

tests/test_http_parser.o: tests/test_http_parser.cc.o

.PHONY : tests/test_http_parser.o

# target to build an object file
tests/test_http_parser.cc.o:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cc.o
.PHONY : tests/test_http_parser.cc.o

tests/test_http_parser.i: tests/test_http_parser.cc.i

.PHONY : tests/test_http_parser.i

# target to preprocess a source file
tests/test_http_parser.cc.i:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cc.i
.PHONY : tests/test_http_parser.cc.i

tests/test_http_parser.s: tests/test_http_parser.cc.s

.PHONY : tests/test_http_parser.s

# target to generate assembly for a file
tests/test_http_parser.cc.s:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cc.s
.PHONY : tests/test_http_parser.cc.s

tests/test_http_server.o: tests/test_http_server.cc.o

.PHONY : tests/test_http_server.o

# target to build an object file
tests/test_http_server.cc.o:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cc.o
.PHONY : tests/test_http_server.cc.o

tests/test_http_server.i: tests/test_http_server.cc.i

.PHONY : tests/test_http_server.i

# target to preprocess a source file
tests/test_http_server.cc.i:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cc.i
.PHONY : tests/test_http_server.cc.i

tests/test_http_server.s: tests/test_http_server.cc.s

.PHONY : tests/test_http_server.s

# target to generate assembly for a file
tests/test_http_server.cc.s:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cc.s
.PHONY : tests/test_http_server.cc.s

tests/test_iomanager.o: tests/test_iomanager.cc.o

.PHONY : tests/test_iomanager.o

# target to build an object file
tests/test_iomanager.cc.o:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.o
.PHONY : tests/test_iomanager.cc.o

tests/test_iomanager.i: tests/test_iomanager.cc.i

.PHONY : tests/test_iomanager.i

# target to preprocess a source file
tests/test_iomanager.cc.i:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.i
.PHONY : tests/test_iomanager.cc.i

tests/test_iomanager.s: tests/test_iomanager.cc.s

.PHONY : tests/test_iomanager.s

# target to generate assembly for a file
tests/test_iomanager.cc.s:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.s
.PHONY : tests/test_iomanager.cc.s

tests/test_scheduler.o: tests/test_scheduler.cc.o

.PHONY : tests/test_scheduler.o

# target to build an object file
tests/test_scheduler.cc.o:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.o
.PHONY : tests/test_scheduler.cc.o

tests/test_scheduler.i: tests/test_scheduler.cc.i

.PHONY : tests/test_scheduler.i

# target to preprocess a source file
tests/test_scheduler.cc.i:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.i
.PHONY : tests/test_scheduler.cc.i

tests/test_scheduler.s: tests/test_scheduler.cc.s

.PHONY : tests/test_scheduler.s

# target to generate assembly for a file
tests/test_scheduler.cc.s:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.s
.PHONY : tests/test_scheduler.cc.s

tests/test_socket.o: tests/test_socket.cc.o

.PHONY : tests/test_socket.o

# target to build an object file
tests/test_socket.cc.o:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cc.o
.PHONY : tests/test_socket.cc.o

tests/test_socket.i: tests/test_socket.cc.i

.PHONY : tests/test_socket.i

# target to preprocess a source file
tests/test_socket.cc.i:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cc.i
.PHONY : tests/test_socket.cc.i

tests/test_socket.s: tests/test_socket.cc.s

.PHONY : tests/test_socket.s

# target to generate assembly for a file
tests/test_socket.cc.s:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cc.s
.PHONY : tests/test_socket.cc.s

tests/test_tcp_server.o: tests/test_tcp_server.cc.o

.PHONY : tests/test_tcp_server.o

# target to build an object file
tests/test_tcp_server.cc.o:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cc.o
.PHONY : tests/test_tcp_server.cc.o

tests/test_tcp_server.i: tests/test_tcp_server.cc.i

.PHONY : tests/test_tcp_server.i

# target to preprocess a source file
tests/test_tcp_server.cc.i:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cc.i
.PHONY : tests/test_tcp_server.cc.i

tests/test_tcp_server.s: tests/test_tcp_server.cc.s

.PHONY : tests/test_tcp_server.s

# target to generate assembly for a file
tests/test_tcp_server.cc.s:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cc.s
.PHONY : tests/test_tcp_server.cc.s

tests/test_thread.o: tests/test_thread.cc.o

.PHONY : tests/test_thread.o

# target to build an object file
tests/test_thread.cc.o:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.o
.PHONY : tests/test_thread.cc.o

tests/test_thread.i: tests/test_thread.cc.i

.PHONY : tests/test_thread.i

# target to preprocess a source file
tests/test_thread.cc.i:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.i
.PHONY : tests/test_thread.cc.i

tests/test_thread.s: tests/test_thread.cc.s

.PHONY : tests/test_thread.s

# target to generate assembly for a file
tests/test_thread.cc.s:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.s
.PHONY : tests/test_thread.cc.s

tests/test_util.o: tests/test_util.cc.o

.PHONY : tests/test_util.o

# target to build an object file
tests/test_util.cc.o:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.o
.PHONY : tests/test_util.cc.o

tests/test_util.i: tests/test_util.cc.i

.PHONY : tests/test_util.i

# target to preprocess a source file
tests/test_util.cc.i:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.i
.PHONY : tests/test_util.cc.i

tests/test_util.s: tests/test_util.cc.s

.PHONY : tests/test_util.s

# target to generate assembly for a file
tests/test_util.cc.s:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.s
.PHONY : tests/test_util.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... my_http_server"
	@echo "... echo_server"
	@echo "... test_http_connection"
	@echo "... test_http"
	@echo "... test_config"
	@echo "... test_http_parser"
	@echo "... hxf"
	@echo "... test_tcp_server"
	@echo "... test_bytearray"
	@echo "... test"
	@echo "... test_thread"
	@echo "... test_util"
	@echo "... test_fiber"
	@echo "... test_http_server"
	@echo "... test_address"
	@echo "... test_scheduler"
	@echo "... test_iomanager"
	@echo "... test_hook"
	@echo "... test_socket"
	@echo "... example/echo_server.o"
	@echo "... example/echo_server.i"
	@echo "... example/echo_server.s"
	@echo "... hxf/address.o"
	@echo "... hxf/address.i"
	@echo "... hxf/address.s"
	@echo "... hxf/bytearray.o"
	@echo "... hxf/bytearray.i"
	@echo "... hxf/bytearray.s"
	@echo "... hxf/config.o"
	@echo "... hxf/config.i"
	@echo "... hxf/config.s"
	@echo "... hxf/fd_manager.o"
	@echo "... hxf/fd_manager.i"
	@echo "... hxf/fd_manager.s"
	@echo "... hxf/fiber.o"
	@echo "... hxf/fiber.i"
	@echo "... hxf/fiber.s"
	@echo "... hxf/hook.o"
	@echo "... hxf/hook.i"
	@echo "... hxf/hook.s"
	@echo "... hxf/http/http.o"
	@echo "... hxf/http/http.i"
	@echo "... hxf/http/http.s"
	@echo "... hxf/http/http11_parser.rl.o"
	@echo "... hxf/http/http11_parser.rl.i"
	@echo "... hxf/http/http11_parser.rl.s"
	@echo "... hxf/http/http_connection.o"
	@echo "... hxf/http/http_connection.i"
	@echo "... hxf/http/http_connection.s"
	@echo "... hxf/http/http_parser.o"
	@echo "... hxf/http/http_parser.i"
	@echo "... hxf/http/http_parser.s"
	@echo "... hxf/http/http_server.o"
	@echo "... hxf/http/http_server.i"
	@echo "... hxf/http/http_server.s"
	@echo "... hxf/http/http_session.o"
	@echo "... hxf/http/http_session.i"
	@echo "... hxf/http/http_session.s"
	@echo "... hxf/http/httpclient_parser.rl.o"
	@echo "... hxf/http/httpclient_parser.rl.i"
	@echo "... hxf/http/httpclient_parser.rl.s"
	@echo "... hxf/http/servlet.o"
	@echo "... hxf/http/servlet.i"
	@echo "... hxf/http/servlet.s"
	@echo "... hxf/iomanager.o"
	@echo "... hxf/iomanager.i"
	@echo "... hxf/iomanager.s"
	@echo "... hxf/log.o"
	@echo "... hxf/log.i"
	@echo "... hxf/log.s"
	@echo "... hxf/scheduler.o"
	@echo "... hxf/scheduler.i"
	@echo "... hxf/scheduler.s"
	@echo "... hxf/socket.o"
	@echo "... hxf/socket.i"
	@echo "... hxf/socket.s"
	@echo "... hxf/socket_stream.o"
	@echo "... hxf/socket_stream.i"
	@echo "... hxf/socket_stream.s"
	@echo "... hxf/stream.o"
	@echo "... hxf/stream.i"
	@echo "... hxf/stream.s"
	@echo "... hxf/tcp_server.o"
	@echo "... hxf/tcp_server.i"
	@echo "... hxf/tcp_server.s"
	@echo "... hxf/thread.o"
	@echo "... hxf/thread.i"
	@echo "... hxf/thread.s"
	@echo "... hxf/timer.o"
	@echo "... hxf/timer.i"
	@echo "... hxf/timer.s"
	@echo "... hxf/uri.rl.o"
	@echo "... hxf/uri.rl.i"
	@echo "... hxf/uri.rl.s"
	@echo "... hxf/util.o"
	@echo "... hxf/util.i"
	@echo "... hxf/util.s"
	@echo "... sample/my_http_server.o"
	@echo "... sample/my_http_server.i"
	@echo "... sample/my_http_server.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
	@echo "... tests/test_address.o"
	@echo "... tests/test_address.i"
	@echo "... tests/test_address.s"
	@echo "... tests/test_bytearray.o"
	@echo "... tests/test_bytearray.i"
	@echo "... tests/test_bytearray.s"
	@echo "... tests/test_config.o"
	@echo "... tests/test_config.i"
	@echo "... tests/test_config.s"
	@echo "... tests/test_fiber.o"
	@echo "... tests/test_fiber.i"
	@echo "... tests/test_fiber.s"
	@echo "... tests/test_hook.o"
	@echo "... tests/test_hook.i"
	@echo "... tests/test_hook.s"
	@echo "... tests/test_http.o"
	@echo "... tests/test_http.i"
	@echo "... tests/test_http.s"
	@echo "... tests/test_http_connection.o"
	@echo "... tests/test_http_connection.i"
	@echo "... tests/test_http_connection.s"
	@echo "... tests/test_http_parser.o"
	@echo "... tests/test_http_parser.i"
	@echo "... tests/test_http_parser.s"
	@echo "... tests/test_http_server.o"
	@echo "... tests/test_http_server.i"
	@echo "... tests/test_http_server.s"
	@echo "... tests/test_iomanager.o"
	@echo "... tests/test_iomanager.i"
	@echo "... tests/test_iomanager.s"
	@echo "... tests/test_scheduler.o"
	@echo "... tests/test_scheduler.i"
	@echo "... tests/test_scheduler.s"
	@echo "... tests/test_socket.o"
	@echo "... tests/test_socket.i"
	@echo "... tests/test_socket.s"
	@echo "... tests/test_tcp_server.o"
	@echo "... tests/test_tcp_server.i"
	@echo "... tests/test_tcp_server.s"
	@echo "... tests/test_thread.o"
	@echo "... tests/test_thread.i"
	@echo "... tests/test_thread.s"
	@echo "... tests/test_util.o"
	@echo "... tests/test_util.i"
	@echo "... tests/test_util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

